new CI workflow

diff --git a/workflow/ci.yml b/workflow/ci.yml
--- a/workflow/ci.yml
+++ b/workflow/ci.yml
@@ -27,3 +27,32 @@ jobs:
 
       - name: Run Playwright tests
         run: npx playwright test
+        continue-on-error: true
+
+      - name: Upload allure results
+        uses: actions/upload-artifact@v4
+        if: always()
+        with:
+          name: allure-results
+          path: allure-results
+          retention-days: 14
+
+      - name: Debug allure-results
+        if: always()
+        run: ls -R allure-results || echo "❌ allure-results folder missing"
+
+      - name: Install Allure
+        if: always()
+        run: npm install -g allure-commandline --save-dev
+
+      - name: Generate Allure report
+        if: always()
+        run: allure generate allure-results --clean -o allure-report
+
+      - name: Upload Allure report
+        if: always()
+        uses: actions/upload-artifact@v4
+        with:
+          name: allure-report
+          path: allure-report
+          retention-days: 14
