new CI workflow07

diff --git a/.github/workflows/playwright.yml b/.github/workflows/playwright.yml
--- a/.github/workflows/playwright.yml
+++ b/.github/workflows/playwright.yml
@@ -5,6 +5,10 @@ on:
     branches: ["main"]
   pull_request:
 
+permissions:
+  contents: read
+  checks: write
+
 jobs:
   test-and-deploy: # 👈 ต้องมี jobs.<jobid>
     runs-on: ubuntu-latest
@@ -22,9 +26,16 @@ jobs:
       - name: Install
         run: npm ci
 
+      - name: Setup Playwright
+        run: npx playwright install --with-deps
+
       - name: Run Playwright tests
-        run: npx playwright test
+        run: npx playwright test --reporter=list,json=json-results/results.json
         continue-on-error: true
+
+      - name: Debug json-results
+        if: always()
+        run: ls -R json-results || echo "❌ json-results folder missing"
 
       # -------------------------------
       # Allure Reports
@@ -82,6 +93,12 @@ jobs:
       - name: Check Netlify version
         if: always()
         run: netlify --version
+
+      - name: Debug GitHub Ref
+        run: |
+          echo "github.ref      = ${{ github.ref }}"
+          echo "github.ref_name = ${{ github.ref_name }}"
+          echo "github.event_name = ${{ github.event_name }}"
 
       - name: Deploy Allure report to Netlify (Production)
         if: github.ref == 'refs/heads/main'
